// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/gremlin/graph/dsl"
)

// Data is the predicate function for data builders.
type Data func(*dsl.Traversal)

// MetaData is the predicate function for metadata builders.
type MetaData func(*dsl.Traversal)

// ReferenceData is the predicate function for referencedata builders.
type ReferenceData func(*dsl.Traversal)
