// Code generated by entc, DO NOT EDIT.

package data

const (
	// Label holds the string label denoting the data type in the database.
	Label = "data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldContext holds the string denoting the context field in the database.
	FieldContext = "context"

	// EdgeHasTable holds the string denoting the has_table edge name in mutations.
	EdgeHasTable = "has_table"
	// EdgeHasField holds the string denoting the has_field edge name in mutations.
	EdgeHasField = "has_field"

	// HasTableLabel holds the string label denoting the has_table edge type in the database.
	HasTableLabel = "data_has_table"
	// HasFieldLabel holds the string label denoting the has_field edge type in the database.
	HasFieldLabel = "data_has_field"
)

var (
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
	// DefaultContext holds the default value on creation for the context field.
	DefaultContext string
)
