-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entity.Object.Entity exposing (..)

import Entity.InputObject
import Entity.Interface
import Entity.Object
import Entity.Scalar
import Entity.ScalarCodecs
import Entity.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias ConnectionsOptionalArguments =
    { id : OptionalArgument Entity.ScalarCodecs.Id
    , context : OptionalArgument String
    }


{-| Get Entity connections by ID

  - id - The ID of the Entity
  - context - The context of the Connection

-}
connections :
    (ConnectionsOptionalArguments -> ConnectionsOptionalArguments)
    -> SelectionSet decodesTo Entity.Object.Entity
    -> SelectionSet (List decodesTo) Entity.Object.Entity
connections fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { id = Absent, context = Absent }

        optionalArgs____ =
            [ Argument.optional "id" filledInOptionals____.id (Entity.ScalarCodecs.codecs |> Entity.Scalar.unwrapEncoder .codecId), Argument.optional "context" filledInOptionals____.context Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "connections" optionalArgs____ object____ (identity >> Decode.list)


{-| The context of the Entity
-}
context : SelectionSet String Entity.Object.Entity
context =
    Object.selectionForField "String" "context" [] Decode.string


{-| The ID of the Entity
-}
id : SelectionSet Entity.ScalarCodecs.Id Entity.Object.Entity
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Entity.ScalarCodecs.codecs |> Entity.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of the Entity
-}
name : SelectionSet String Entity.Object.Entity
name =
    Object.selectionForField "String" "name" [] Decode.string
