// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/gremlin"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl/g"
	"github.com/jhole89/orbital/ent/metadata"
)

// MetaDataCreate is the builder for creating a MetaData entity.
type MetaDataCreate struct {
	config
	mutation *MetaDataMutation
	hooks    []Hook
}

// Mutation returns the MetaDataMutation object of the builder.
func (mdc *MetaDataCreate) Mutation() *MetaDataMutation {
	return mdc.mutation
}

// Save creates the MetaData in the database.
func (mdc *MetaDataCreate) Save(ctx context.Context) (*MetaData, error) {
	var (
		err  error
		node *MetaData
	)
	if len(mdc.hooks) == 0 {
		if err = mdc.check(); err != nil {
			return nil, err
		}
		node, err = mdc.gremlinSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MetaDataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mdc.check(); err != nil {
				return nil, err
			}
			mdc.mutation = mutation
			node, err = mdc.gremlinSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mdc.hooks) - 1; i >= 0; i-- {
			mut = mdc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mdc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mdc *MetaDataCreate) SaveX(ctx context.Context) *MetaData {
	v, err := mdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (mdc *MetaDataCreate) check() error {
	return nil
}

func (mdc *MetaDataCreate) gremlinSave(ctx context.Context) (*MetaData, error) {
	res := &gremlin.Response{}
	query, bindings := mdc.gremlin().Query()
	if err := mdc.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	if err, ok := isConstantError(res); ok {
		return nil, err
	}
	md := &MetaData{config: mdc.config}
	if err := md.FromResponse(res); err != nil {
		return nil, err
	}
	return md, nil
}

func (mdc *MetaDataCreate) gremlin() *dsl.Traversal {
	v := g.AddV(metadata.Label)
	return v.ValueMap(true)
}

// MetaDataCreateBulk is the builder for creating a bulk of MetaData entities.
type MetaDataCreateBulk struct {
	config
	builders []*MetaDataCreate
}
