// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/gremlin"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl/__"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl/g"
	"github.com/jhole89/orbital/ent/metadata"
	"github.com/jhole89/orbital/ent/predicate"
)

// MetaDataQuery is the builder for querying MetaData entities.
type MetaDataQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.MetaData
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Where adds a new predicate for the builder.
func (mdq *MetaDataQuery) Where(ps ...predicate.MetaData) *MetaDataQuery {
	mdq.predicates = append(mdq.predicates, ps...)
	return mdq
}

// Limit adds a limit step to the query.
func (mdq *MetaDataQuery) Limit(limit int) *MetaDataQuery {
	mdq.limit = &limit
	return mdq
}

// Offset adds an offset step to the query.
func (mdq *MetaDataQuery) Offset(offset int) *MetaDataQuery {
	mdq.offset = &offset
	return mdq
}

// Order adds an order step to the query.
func (mdq *MetaDataQuery) Order(o ...OrderFunc) *MetaDataQuery {
	mdq.order = append(mdq.order, o...)
	return mdq
}

// First returns the first MetaData entity in the query. Returns *NotFoundError when no metadata was found.
func (mdq *MetaDataQuery) First(ctx context.Context) (*MetaData, error) {
	nodes, err := mdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{metadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mdq *MetaDataQuery) FirstX(ctx context.Context) *MetaData {
	node, err := mdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MetaData id in the query. Returns *NotFoundError when no id was found.
func (mdq *MetaDataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{metadata.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (mdq *MetaDataQuery) FirstXID(ctx context.Context) int {
	id, err := mdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only MetaData entity in the query, returns an error if not exactly one entity was returned.
func (mdq *MetaDataQuery) Only(ctx context.Context) (*MetaData, error) {
	nodes, err := mdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{metadata.Label}
	default:
		return nil, &NotSingularError{metadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mdq *MetaDataQuery) OnlyX(ctx context.Context) *MetaData {
	node, err := mdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only MetaData id in the query, returns an error if not exactly one id was returned.
func (mdq *MetaDataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = &NotSingularError{metadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mdq *MetaDataQuery) OnlyIDX(ctx context.Context) int {
	id, err := mdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MetaDataSlice.
func (mdq *MetaDataQuery) All(ctx context.Context) ([]*MetaData, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mdq.gremlinAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mdq *MetaDataQuery) AllX(ctx context.Context) []*MetaData {
	nodes, err := mdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MetaData ids.
func (mdq *MetaDataQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mdq.Select(metadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mdq *MetaDataQuery) IDsX(ctx context.Context) []int {
	ids, err := mdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mdq *MetaDataQuery) Count(ctx context.Context) (int, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mdq.gremlinCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mdq *MetaDataQuery) CountX(ctx context.Context) int {
	count, err := mdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mdq *MetaDataQuery) Exist(ctx context.Context) (bool, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mdq.gremlinExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mdq *MetaDataQuery) ExistX(ctx context.Context) bool {
	exist, err := mdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mdq *MetaDataQuery) Clone() *MetaDataQuery {
	return &MetaDataQuery{
		config:     mdq.config,
		limit:      mdq.limit,
		offset:     mdq.offset,
		order:      append([]OrderFunc{}, mdq.order...),
		unique:     append([]string{}, mdq.unique...),
		predicates: append([]predicate.MetaData{}, mdq.predicates...),
		// clone intermediate query.
		gremlin: mdq.gremlin.Clone(),
		path:    mdq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (mdq *MetaDataQuery) GroupBy(field string, fields ...string) *MetaDataGroupBy {
	group := &MetaDataGroupBy{config: mdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *dsl.Traversal, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mdq.gremlinQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
func (mdq *MetaDataQuery) Select(field string, fields ...string) *MetaDataSelect {
	selector := &MetaDataSelect{config: mdq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *dsl.Traversal, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mdq.gremlinQuery(), nil
	}
	return selector
}

func (mdq *MetaDataQuery) prepareQuery(ctx context.Context) error {
	if mdq.path != nil {
		prev, err := mdq.path(ctx)
		if err != nil {
			return err
		}
		mdq.gremlin = prev
	}
	return nil
}

func (mdq *MetaDataQuery) gremlinAll(ctx context.Context) ([]*MetaData, error) {
	res := &gremlin.Response{}
	query, bindings := mdq.gremlinQuery().ValueMap(true).Query()
	if err := mdq.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	var mds MetaDataSlice
	if err := mds.FromResponse(res); err != nil {
		return nil, err
	}
	mds.config(mdq.config)
	return mds, nil
}

func (mdq *MetaDataQuery) gremlinCount(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := mdq.gremlinQuery().Count().Query()
	if err := mdq.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (mdq *MetaDataQuery) gremlinExist(ctx context.Context) (bool, error) {
	res := &gremlin.Response{}
	query, bindings := mdq.gremlinQuery().HasNext().Query()
	if err := mdq.driver.Exec(ctx, query, bindings, res); err != nil {
		return false, err
	}
	return res.ReadBool()
}

func (mdq *MetaDataQuery) gremlinQuery() *dsl.Traversal {
	v := g.V().HasLabel(metadata.Label)
	if mdq.gremlin != nil {
		v = mdq.gremlin.Clone()
	}
	for _, p := range mdq.predicates {
		p(v)
	}
	if len(mdq.order) > 0 {
		v.Order()
		for _, p := range mdq.order {
			p(v)
		}
	}
	switch limit, offset := mdq.limit, mdq.offset; {
	case limit != nil && offset != nil:
		v.Range(*offset, *offset+*limit)
	case offset != nil:
		v.Range(*offset, math.MaxInt32)
	case limit != nil:
		v.Limit(*limit)
	}
	if unique := mdq.unique; len(unique) == 0 {
		v.Dedup()
	}
	return v
}

// MetaDataGroupBy is the builder for group-by MetaData entities.
type MetaDataGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mdgb *MetaDataGroupBy) Aggregate(fns ...AggregateFunc) *MetaDataGroupBy {
	mdgb.fns = append(mdgb.fns, fns...)
	return mdgb
}

// Scan applies the group-by query and scan the result into the given value.
func (mdgb *MetaDataGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mdgb.path(ctx)
	if err != nil {
		return err
	}
	mdgb.gremlin = query
	return mdgb.gremlinScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: MetaDataGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) StringsX(ctx context.Context) []string {
	v, err := mdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) StringX(ctx context.Context) string {
	v, err := mdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: MetaDataGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) IntsX(ctx context.Context) []int {
	v, err := mdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) IntX(ctx context.Context) int {
	v, err := mdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: MetaDataGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: MetaDataGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (mdgb *MetaDataGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mdgb *MetaDataGroupBy) BoolX(ctx context.Context) bool {
	v, err := mdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mdgb *MetaDataGroupBy) gremlinScan(ctx context.Context, v interface{}) error {
	res := &gremlin.Response{}
	query, bindings := mdgb.gremlinQuery().Query()
	if err := mdgb.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(mdgb.fields)+len(mdgb.fns) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}

func (mdgb *MetaDataGroupBy) gremlinQuery() *dsl.Traversal {
	var (
		trs   []interface{}
		names []interface{}
	)
	for _, fn := range mdgb.fns {
		name, tr := fn("p", "")
		trs = append(trs, tr)
		names = append(names, name)
	}
	for _, f := range mdgb.fields {
		names = append(names, f)
		trs = append(trs, __.As("p").Unfold().Values(f).As(f))
	}
	return mdgb.gremlin.Group().
		By(__.Values(mdgb.fields...).Fold()).
		By(__.Fold().Match(trs...).Select(names...)).
		Select(dsl.Values).
		Next()
}

// MetaDataSelect is the builder for select fields of MetaData entities.
type MetaDataSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Scan applies the selector query and scan the result into the given value.
func (mds *MetaDataSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := mds.path(ctx)
	if err != nil {
		return err
	}
	mds.gremlin = query
	return mds.gremlinScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mds *MetaDataSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: MetaDataSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mds *MetaDataSelect) StringsX(ctx context.Context) []string {
	v, err := mds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mds *MetaDataSelect) StringX(ctx context.Context) string {
	v, err := mds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: MetaDataSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mds *MetaDataSelect) IntsX(ctx context.Context) []int {
	v, err := mds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mds *MetaDataSelect) IntX(ctx context.Context) int {
	v, err := mds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: MetaDataSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mds *MetaDataSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mds *MetaDataSelect) Float64X(ctx context.Context) float64 {
	v, err := mds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: MetaDataSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mds *MetaDataSelect) BoolsX(ctx context.Context) []bool {
	v, err := mds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (mds *MetaDataSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{metadata.Label}
	default:
		err = fmt.Errorf("ent: MetaDataSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mds *MetaDataSelect) BoolX(ctx context.Context) bool {
	v, err := mds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mds *MetaDataSelect) gremlinScan(ctx context.Context, v interface{}) error {
	var (
		traversal *dsl.Traversal
		res       = &gremlin.Response{}
	)
	if len(mds.fields) == 1 {
		if mds.fields[0] != metadata.FieldID {
			traversal = mds.gremlin.Values(mds.fields...)
		} else {
			traversal = mds.gremlin.ID()
		}
	} else {
		fields := make([]interface{}, len(mds.fields))
		for i, f := range mds.fields {
			fields[i] = f
		}
		traversal = mds.gremlin.ValueMap(fields...)
	}
	query, bindings := traversal.Query()
	if err := mds.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(mds.fields) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}
