// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/gremlin"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl/__"
	"github.com/facebook/ent/dialect/gremlin/graph/dsl/g"
	"github.com/jhole89/orbital/ent/predicate"
	"github.com/jhole89/orbital/ent/referencedata"
)

// ReferenceDataDelete is the builder for deleting a ReferenceData entity.
type ReferenceDataDelete struct {
	config
	hooks      []Hook
	mutation   *ReferenceDataMutation
	predicates []predicate.ReferenceData
}

// Where adds a new predicate to the delete builder.
func (rdd *ReferenceDataDelete) Where(ps ...predicate.ReferenceData) *ReferenceDataDelete {
	rdd.predicates = append(rdd.predicates, ps...)
	return rdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rdd *ReferenceDataDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rdd.hooks) == 0 {
		affected, err = rdd.gremlinExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ReferenceDataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rdd.mutation = mutation
			affected, err = rdd.gremlinExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rdd.hooks) - 1; i >= 0; i-- {
			mut = rdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rdd *ReferenceDataDelete) ExecX(ctx context.Context) int {
	n, err := rdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rdd *ReferenceDataDelete) gremlinExec(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := rdd.gremlin().Query()
	if err := rdd.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (rdd *ReferenceDataDelete) gremlin() *dsl.Traversal {
	t := g.V().HasLabel(referencedata.Label)
	for _, p := range rdd.predicates {
		p(t)
	}
	return t.SideEffect(__.Drop()).Count()
}

// ReferenceDataDeleteOne is the builder for deleting a single ReferenceData entity.
type ReferenceDataDeleteOne struct {
	rdd *ReferenceDataDelete
}

// Exec executes the deletion query.
func (rddo *ReferenceDataDeleteOne) Exec(ctx context.Context) error {
	n, err := rddo.rdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{referencedata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rddo *ReferenceDataDeleteOne) ExecX(ctx context.Context) {
	rddo.rdd.ExecX(ctx)
}
