// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/jhole89/orbital/ent/data"
	"github.com/jhole89/orbital/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	dataFields := schema.Data{}.Fields()
	_ = dataFields
	// dataDescName is the schema descriptor for name field.
	dataDescName := dataFields[0].Descriptor()
	// data.DefaultName holds the default value on creation for the name field.
	data.DefaultName = dataDescName.Default.(string)
	// dataDescContext is the schema descriptor for context field.
	dataDescContext := dataFields[1].Descriptor()
	// data.DefaultContext holds the default value on creation for the context field.
	data.DefaultContext = dataDescContext.Default.(string)
}
