// Code generated by entc, DO NOT EDIT.

package referencedata

const (
	// Label holds the string label denoting the referencedata type in the database.
	Label = "reference_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
)
