// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/jhole89/orbital/ent/runtime.go

const (
	Version = "v0.4.3"                                          // Version of ent codegen.
	Sum     = "h1:ds9HENceKzpGBgCRlkZNq6TqBIegwKcF3e5reuV9Z0M=" // Sum of ent codegen.
)
