-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entity.ScalarCodecs exposing (..)

import Entity.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Entity.Scalar.Id


codecs : Entity.Scalar.Codecs Id
codecs =
    Entity.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
