// Code generated by entc, DO NOT EDIT.

package metadata

const (
	// Label holds the string label denoting the metadata type in the database.
	Label = "meta_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
)
