name: Publish Latest Pipeline

on:
  push:
    branches:
      - "main"
      - "feat/publish-component-containers"

jobs:
  publish-metrics:
    runs-on: ubuntu-latest
    name: Metrics Pipeline
    steps:
      - uses: actions/checkout@v2

      - name: Publish GoCardReport
        uses: creekorful/goreportcard-action@v1.0
        with:
          path: app

  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Docker Latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Go app
        uses: docker/build-push-action@v2
        with:
          context: app
          push: true
          tags: |
            ${{ github.repository }}/app:latest
            ghcr.io/${{ github.repository }}/app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GHCR_TOKEN }}

      - name: Build and push UI
        uses: docker/build-push-action@v2
        with:
          context: ui
          push: true
          tags: |
            ${{ github.repository }}/ui:latest
            ghcr.io/${{ github.repository }}/ui:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GHCR_TOKEN }}
