name: Publish Latest Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  publish-metrics:
    runs-on: ubuntu-latest
    name: Metrics Pipeline
    steps:
      - uses: actions/checkout@v3

      - name: Publish GoCardReport
        uses: creekorful/goreportcard-action@v1.0
        with:
          path: app

  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Docker Latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Go app
        uses: docker/build-push-action@v2
        with:
          context: app
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}-app:latest
          push: true

      - name: Build and push UI
        uses: docker/build-push-action@v2
        with:
          context: ui
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}-ui:latest
          push: true
