name: Versioned Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  gh-release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Release Pipeline
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

  docker-release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Docker Release Pipeline
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Go app
        uses: docker/build-push-action@v2
        with:
          context: app
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}-app:${{ github.ref }}
          push: true

      - name: Build and push UI
        uses: docker/build-push-action@v2
        with:
          context: ui
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}-ui:${{ github.ref }}
          push: true
